/**
 * Custom Worker entry: OpenNext's fetch handler plus a `scheduled` handler for
 * the 15-minute DocuSign backup poll (see `triggers.crons` in wrangler.jsonc).
 * The cron calls the Worker's own fetch handler in-process so the poll runs
 * inside the normal Next.js request context (bindings, process.env, D1/R2).
 */
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore -- generated by `opennextjs-cloudflare build`
import { default as handler } from "./.open-next/worker.js";
import { CRON_AUTH_HEADER, DOCUSIGN_POLL_PATH, cronAuthToken } from "./lib/cron-auth";

type Env = { ADMIN_SESSION_SECRET?: string; APP_URL?: string } & Record<string, unknown>;
type Ctx = { waitUntil(promise: Promise<unknown>): void; passThroughOnException(): void };

export default {
  fetch: handler.fetch,

  async scheduled(event: { cron: string; scheduledTime: number }, env: Env, ctx: Ctx) {
    const secret = env.ADMIN_SESSION_SECRET;
    if (!secret) {
      console.warn("[docusign-poll] ADMIN_SESSION_SECRET is not set; skipping cron poll");
      return;
    }
    const origin = env.APP_URL || "https://canaanpreserve.com";
    const request = new Request(new URL(DOCUSIGN_POLL_PATH, origin), {
      method: "POST",
      headers: { [CRON_AUTH_HEADER]: await cronAuthToken(secret) },
    });
    const response: Response = await handler.fetch(request, env, ctx);
    const body = await response.text();
    if (!response.ok) {
      console.warn(`[docusign-poll] cron ${event.cron} → HTTP ${response.status}`, body.slice(0, 300));
      return;
    }
    console.log(`[docusign-poll] cron ${event.cron} → ${body.slice(0, 300)}`);
  },
};

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore -- generated by `opennextjs-cloudflare build`
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";
